import type { FinanceLedgerPreviewDto } from '../finance/finance-ledger-preview.types.js';
import type { NavlungoCreatePostRequestSummaryDto } from '../shipping/shipping-execution.types.js';

export type OrderSummaryDto = {
  id: string;
  sourceShopifyOrderId: string;
  sourceShopifyOrderNumber: string;
  vendorId: string;
  assignedVendorId: string;
  originalVendorId: string;
  allocationStatus: string;
  fulfillmentStatus: string;
  shippingStatus: string;
  carrier: string | null;
  trackingNumber: string | null;
  trackingUrl: string | null;
  fulfilledAt: string | null;
  shipmentCreatedAt: string | null;
  shipmentUpdatedAt: string | null;
  totalAmount: string;
  lineItemCount: number;
  createdAt: string;
  updatedAt: string;
};

export type ShopifyFulfillmentSyncDto = {
  status: 'synced' | 'pending' | 'failed' | 'not_available';
  fulfillmentOrderIdPresent: boolean;
  fulfillmentIdPresent: boolean;
  syncStatus: string | null;
  skippedReason: string | null;
  errorMessage: string | null;
  lastAttemptedAt: string | null;
};

export type ShopifyReturnSignalDiscoveryDto = {
  topic: string;
  receivedAt: string;
  topLevelPayloadKeys: string[];
  orderIdPresent: boolean;
  returnIdPresent: boolean;
  lineItemIdsPresent: boolean;
  refundIdPresent: boolean;
  financialStatus: string | null;
  fulfillmentStatus: string | null;
  matchedOrderId: string | null;
  matchedByField: string | null;
};

export type OrderDetailLineItemDto = {
  id: string;
  sourceLineItemId: string;
  sourceVariantId: string | null;
  sku: string | null;
  title: string | null;
  imageUrl: string | null;
  quantity: number;
  lineAmount: string;
  shopifyProductId: string | null;
  unitPriceVatIncluded: string | null;
  lineTotalVatIncluded: string | null;
  lineTaxAmount: string | null;
  vatRate: string | null;
};

export type OrderSnapshotDto = {
  shopifyCreatedAt: string | null;
  currency: string | null;
  financialStatus: string | null;
  paymentGatewayName: string | null;
  taxesIncluded: boolean | null;
  orderTaxAmount: string | null;
  shippingAmount: string | null;
  discountAmount: string | null;
  orderNote: string | null;
  orderTags: string[];
  vendorIntegrationStatus: string | null;
  vendorIntegrationStatusMessage: string | null;
  vendorIntegrationStatusUpdatedAt: string | null;
  vendorIntegrationProvider: string | null;
  vendorIntegrationTrackingUrl: string | null;
  vendorIntegrationShippedAt: string | null;
  vendorInvoiceNumber: string | null;
  vendorInvoiceDate: string | null;
  vendorInvoiceUrl: string | null;
  vendorInvoiceAmount: string | null;
  vendorInvoiceReceivedAt: string | null;
  billingAddress: {
    fullName: string | null;
    company: string | null;
    phone: string | null;
    city: string | null;
    district: string | null;
    address1: string | null;
    address2: string | null;
    postcode: string | null;
  };
};

export type OrderAssignmentHistoryDto = {
  id: string;
  action: string;
  fromVendorId: string | null;
  toVendorId: string;
  reason: string | null;
  actorUserId: string | null;
  createdAt: string;
};

export type OrderShipmentExecutionDto = {
  id: string;
  provider: string;
  sourceShopifyOrderId: string | null;
  sourceShopifyOrderNumber: string | null;
  sourceShopifyFulfillmentId: string | null;
  providerShipmentId: string | null;
  providerCarrierName: string | null;
  trackingNumber: string | null;
  trackingUrl: string | null;
  labelUrl: string | null;
  shipmentStatus: string;
  desi: string;
  cargoIntegrationId: string | null;
  warehouseId: string | null;
  shippingCost: string | null;
  shippingVat: string | null;
  currency: string;
  providerStatus: string | null;
  barcode: string | null;
  lastProviderResponseAt: string | null;
  dummyCarrierDetected: boolean;
  webhookReceived: boolean;
  barcodeAssigned: boolean;
  trackingAssigned: boolean;
  returnShipment: {
    provider: 'try_oto';
    returnOrderId: string | null;
    trackingNumber: string | null;
    trackingUrl: string | null;
    labelUrl: string | null;
    barcode: string | null;
    carrierName: string | null;
    status: string | null;
    createdAt: string | null;
    requestKeys: string[];
    responseKeys: string[];
    trackingPresent: boolean;
    labelPresent: boolean;
    labelRetrievalConfirmed: boolean;
    labelRetrievalNote: string | null;
    finalized: boolean;
    labelRetrievable: boolean;
    providerStatusSource: string | null;
    diagnostics: {
      endpoint: string | null;
      httpStatus: number | null;
      requestKeys: string[];
      responseKeys: string[];
      returnProviderIdPresent: boolean;
      returnTrackingPresent: boolean;
      returnBarcodePresent: boolean;
      returnStatus: string | null;
      returnCarrierName: string | null;
      labelFieldPresent: boolean;
      returnLabelSourceChecked: string | null;
      returnTrackingSourceChecked: string | null;
      rawPrintReturnAwbUrlPresent: boolean;
      normalizedReturnLabelUrlPresent: boolean;
      returnLabelPersistenceStage: string | null;
      returnLabelOverwrittenByStaleSnapshot: boolean;
      providerMessage: string | null;
      returnSkippedReason: string | null;
      forwardDeliveryOptionIdPresent: boolean;
      forwardDeliveryOptionIdSource: string | null;
      forwardDeliveryOptionPersistedAt: string | null;
      forwardDeliveryOptionRetainedAfterWebhook: boolean;
      forwardDeliveryOptionRetainedAfterStatusRefresh: boolean;
      returnDeliveryOptionIdPresent: boolean;
      returnDeliveryOptionIdSource: string | null;
      pickupLocationCodePresent: boolean;
      returnItemSkuPresent: boolean;
      returnItemQuantityPresent: boolean;
      createReturnShipmentFinalized: boolean;
      returnDeliveryOptionLookupCalled: boolean;
      returnDeliveryOptionLookupImplemented: boolean;
      returnPriceLookupCalled: boolean;
      returnPriceLookupSuccess: boolean;
      returnPriceLookupOptionCount: number | null;
      selectedReturnPriceOptionIdPresent: boolean;
      reverseCreateShipmentCalled: boolean;
      reverseCreateShipmentSuccess: boolean;
      reverseCreateShipmentResponseKeys: string[];
      reverseCreateShipmentTrackingPresent: boolean;
      reverseCreateShipmentBarcodePresent: boolean;
      reverseCreateShipmentLabelPresent: boolean;
      returnFinalized: boolean;
      returnFinalizationEndpointConfirmed: boolean;
      returnFinalizeEndpointImplemented: boolean;
      returnLabelRetrievable: boolean;
      providerStatusSource: string | null;
    } | null;
    detailsProbe: {
      status: string;
      attemptedAt: string | null;
      endpoint: string | null;
      httpStatus: number | null;
      responseKeys: string[];
      nestedKeys: string[];
      labelLikeFieldsPresent: boolean;
      awbLikeFieldsPresent: boolean;
      pdfLikeFieldsPresent: boolean;
      urlLikeFieldsPresent: boolean;
      trackingPresent: boolean;
      barcodePresent: boolean;
      providerStatus: string | null;
      labelUrlPresent: boolean;
      errorMessage: string | null;
    } | null;
    linkProbe: {
      status: string;
      attemptedAt: string | null;
      endpoint: string | null;
      httpStatus: number | null;
      responseKeys: string[];
      nestedKeys: string[];
      labelLikeFieldsPresent: boolean;
      awbLikeFieldsPresent: boolean;
      pdfLikeFieldsPresent: boolean;
      urlLikeFieldsPresent: boolean;
      actionUrlPresent: boolean;
      trackingPresent: boolean;
      barcodePresent: boolean;
      providerStatus: string | null;
      labelUrlPresent: boolean;
      providerMessage: string | null;
      errorMessage: string | null;
    } | null;
    awbPrintProbe: {
      status: string;
      attemptedAt: string | null;
      endpoint: string | null;
      httpStatus: number | null;
      responseKeys: string[];
      nestedKeys: string[];
      labelLikeFieldsPresent: boolean;
      awbLikeFieldsPresent: boolean;
      pdfLikeFieldsPresent: boolean;
      urlLikeFieldsPresent: boolean;
      trackingPresent: boolean;
      barcodePresent: boolean;
      providerStatus: string | null;
      labelUrlPresent: boolean;
      providerMessage: string | null;
      errorMessage: string | null;
    } | null;
    shopifyReturnLabelUploadProbe: {
      status: string;
      attemptedAt: string | null;
      reverseFulfillmentOrderIdPresent: boolean;
      reverseLineItemIdsPresent: boolean;
      mutationUsed: string | null;
      shopifyUserErrors: Array<{
        field: string[];
        message: string;
      }>;
      reverseDeliveryIdPresent: boolean;
      shopifyReturnIdPresent: boolean;
      trackingAccepted: boolean;
      labelAccepted: boolean;
      returnedCarrierName: string | null;
      carrierNamePresent: boolean;
      trackingOnlyMode: boolean;
      labelInputSent: boolean;
      shopifyCallAttempted: boolean;
      skippedReason: string | null;
      errorMessage: string | null;
    } | null;
  } | null;
  timeline: Array<{
    label: string;
    at: string;
    status: string | null;
  }>;
  createdAt: string;
  updatedAt: string;
  providerResponseSummary?: {
    httpStatus: number | null;
    ok: boolean | null;
    contentType: string | null;
    parsedBodyType: string | null;
    responseKeys: string[];
    providerError: string | null;
    providerErrorMessage?: string | null;
    providerErrorErrors?: unknown;
    providerErrorBodyPreview?: unknown;
    confirmShipmentId?: string | null;
    confirmShippingProviderId?: string | null;
    dryRun: boolean | null;
    disabledGates: string[];
    providerValidationErrors: string[];
    validationErrorKeys?: string[];
    validationErrorMessages?: string[];
    failedFieldNames?: string[];
    validationErrorKeysCount?: number | null;
    failedFieldNamesCount?: number | null;
    validationErrorMessagesCount?: number | null;
    providerValidationErrorsShape?: string | null;
    createPostErrorShape?: string | null;
    topLevelErrorShape?: string | null;
    nestedCreatePostErrorShape?: string | null;
    providerErrorCode?: string | null;
    providerTrackingId?: string | null;
    validationResponseShape?: {
      kind: string;
      topLevelKeys: string[];
    } | null;
    providerShipmentIdPresent: boolean;
    trackingNumberPresent: boolean;
    labelPresent: boolean;
    barcodePresent: boolean;
    notificationUrlIncluded: boolean | null;
    statusField: string | null;
    detectedResponseFormat: string | null;
    responseSnippet: string | null;
    authHeaderMode: string | null;
    requestId: string | null;
    requestPath?: string | null;
    selectedEnvironment?: string | null;
    requestTargetHostname?: string | null;
    providerMode?: string | null;
    providerApiCallAttempted?: boolean | null;
    navlungoRequestSummary?: NavlungoCreatePostRequestSummaryDto | null;
    lastSuccessfulNavlungoRequestSummary?: NavlungoCreatePostRequestSummaryDto | null;
    lastSuccessfulNavlungoRequestSummarySource?: string | null;
    lastSuccessfulNavlungoRequestSummaryReason?: string | null;
    senderAddressIdPresent?: boolean | null;
    senderAddressIdValid?: boolean | null;
    senderUsesAddressId?: boolean | null;
    senderMode?: string | null;
    fullSenderRetryRequested?: boolean | null;
    shopifyFulfillmentSyncAttempted?: boolean | null;
    shopifyFulfillmentSyncSkippedReason?: string | null;
    shopifyFulfillmentSynced?: boolean | null;
    shopifyFulfillmentCancelSyncSkippedReason?: string | null;
    fulfillmentTrackingNumberPresent?: boolean | null;
    fulfillmentTrackingUrlPresent?: boolean | null;
    navlungoCancelAttempted?: boolean | null;
    navlungoCancelHttpStatus?: number | null;
    navlungoCancelSucceeded?: boolean | null;
    navlungoCancelProviderMessage?: string | null;
    navlungoCancelValidationFields?: string[];
    navlungoCancelValidationMessages?: string[];
    navlungoCancelProviderTrackingId?: string | null;
    navlungoCancelledAt?: string | null;
    navlungoUpdateAttempted?: boolean | null;
    navlungoUpdateHttpStatus?: number | null;
    navlungoUpdateSucceeded?: boolean | null;
    navlungoUpdateProviderMessage?: string | null;
    navlungoUpdateValidationFields?: string[];
    navlungoUpdateValidationMessages?: string[];
    navlungoUpdateProviderTrackingId?: string | null;
    navlungoUpdateResponseShape?: {
      kind: string;
      topLevelKeys: string[];
    } | null;
    navlungoUpdateSenderMode?: string | null;
    navlungoUpdateSenderFieldKeys?: string[];
    navlungoUpdateMissingSenderFields?: string[];
    navlungoUpdateRecipientOverridePresent?: boolean | null;
    navlungoUpdateRecipientOverrideKeys?: string[];
    navlungoUpdateSubmittedRecipientOverrideKeys?: string[];
    navlungoUpdateOptionOverrideKeys?: string[];
    navlungoUpdateRecipientOverrides?: Partial<Record<
      'name' | 'phone' | 'email' | 'country' | 'postcode' | 'city' | 'district' | 'address',
      string
    >>;
    navlungoUpdatePostNote?: string | null;
    navlungoUpdateBarcodeFormat?: string | null;
    navlungoUpdatedAt?: string | null;
    shopifyFulfillmentUpdateSyncSkippedReason?: string | null;
    lastProviderStage?: string | null;
    createShipmentCalled?: boolean | null;
    priceComparisonCalled?: boolean | null;
    confirmShippingPriceCalled?: boolean | null;
    getShipmentCalled?: boolean | null;
    barcodeFetchCalled?: boolean | null;
    kargonomiPostCreateDiagnostics?: {
      getShipmentAfterConfirm: {
        httpStatus: number | null;
        contentType: string | null;
        bodyKeys: string[];
        safeFields: unknown;
      } | null;
      barcodeFetch: {
        httpStatus: number | null;
        contentType: string | null;
        topLevelKeys: string[];
        bodyKeys: string[];
        detectedFormat: string | null;
        pdfLikeValuePresent: boolean | null;
        labelUrlPresent: boolean | null;
      } | null;
    } | null;
    payloadDiagnostics?: {
      topLevelKeys: string[];
      customerKeys: string[];
      receiverKeys: string[];
      cargoIntegrationIdPresent: boolean;
      warehouseIdPresent: boolean;
      paymentType: string | null;
      packageType: string | null;
      payorType: string | null;
      kgPresent: boolean;
      kgType: string | null;
      desiPresent: boolean;
      desiType: string | null;
      platformIdPresent: boolean;
      platformDIdPresent: boolean;
      customerPhonePresent: boolean;
      customerDistrictPresent: boolean;
      customerCityPresent: boolean;
      deliveryOptionIdPresent?: boolean;
      addressFieldPresence: {
        customerAddress: boolean;
        customerPostcode: boolean;
        customerCountry: boolean;
        customerCity: boolean;
        customerDistrict: boolean;
      };
    };
    tryOtoFinalization?: {
      createOrderSuccess: boolean | null;
      createShipmentCalled: boolean;
      createShipmentSuccess: boolean | null;
      createShipmentResponseKeys: string[];
      createShipmentProviderMessage: string | null;
      createShipmentProviderErrorCode?: string | null;
      createShipmentEndpoint?: string | null;
      createShipmentResponseStatus?: number | null;
      createShipmentRequestKeys: string[];
      createShipmentDeliveryOptionIdPresent: boolean | null;
      deliveryOptionIdPresent: boolean | null;
      orderStatusValue: string | null;
      deliveryOptionLookupCalled?: boolean;
      deliveryOptionLookupSuccess?: boolean | null;
      deliveryOptionLookupOptionCount?: number | null;
      selectedDeliveryCompanyName?: string | null;
      selectedDeliveryOptionIdPresent?: boolean;
      deliveryOptionLookupErrorMessage?: string | null;
      deliveryOptionLookupEndpoint?: string | null;
      deliveryOptionLookupRequestKeys?: string[];
      deliveryOptionLookupRequestPresence?: {
        pickupLocationCode: boolean;
        originCity: boolean;
        packageWeight: boolean;
        weight?: boolean;
        customerCity: boolean;
        customerCountry: boolean;
        paymentMethod: boolean;
      } | null;
      deliveryOptionLookupSourcePresence?: {
        pickupLocationCode: boolean;
        originCity: boolean;
        packageWeight: boolean;
        customerCity: boolean;
        customerCountry: boolean;
        paymentMethod: boolean;
      } | null;
      deliveryOptionLookupResponseStatus?: number | null;
      deliveryOptionLookupResponseKeys?: string[];
      deliveryOptionLookupResponseBodyKeys?: string[];
      deliveryOptionLookupResponseHasDeliveryOptionId?: boolean | null;
      deliveryOptionLookupResponseHasDeliveryCompanyName?: boolean | null;
      deliveryOptionLookupResponseHasPricing?: boolean | null;
      deliveryOptionLookupResponsePricingKeys?: string[];
      deliveryOptionLookupWeightFieldNames?: string[];
      deliveryOptionLookupNumericWeightPresent?: boolean | null;
      deliveryOptionLookupWeightType?: string | null;
      lastWebhookReceivedAt?: string | null;
      lastWebhookMatchStatus?: string | null;
      lastWebhookMatchedByField?: string | null;
      lastWebhookHttpMethod?: string | null;
      lastWebhookContentType?: string | null;
      lastWebhookStatusField?: string | null;
      lastWebhookStatusMapped?: boolean | null;
      lastWebhookMappedShipmentStatus?: string | null;
      latestProviderStatusSource?: string | null;
      lastWebhookParseError?: string | null;
      webhookSignatureVerificationImplemented?: boolean | null;
      webhookAuthenticityVerification?: {
        mode: 'shared_secret' | 'disabled_dev_only';
        providerNativeSignatureVerified: false;
        note: string;
      } | null;
      webhookWarning?: string | null;
    };
  };
};

export type OrderDetailDto = OrderSummaryDto & {
  customerName: string | null;
  reassignmentRequired: boolean;
  cancellationReason: string | null;
  orderSnapshot: OrderSnapshotDto;
  shopifyFulfillmentSync: ShopifyFulfillmentSyncDto;
  shopifyReturnSignal: ShopifyReturnSignalDiscoveryDto | null;
  financeLedgerPreview?: FinanceLedgerPreviewDto | null;
  lineItems: OrderDetailLineItemDto[];
  assignmentHistory: OrderAssignmentHistoryDto[];
  shipmentExecution: OrderShipmentExecutionDto | null;
};

export type AdminOrderBreakdownLineItemDto = {
  id: string;
  sourceLineItemId: string;
  sourceVariantId: string | null;
  sku: string | null;
  title: string | null;
  imageUrl: string | null;
  quantity: number;
  lineAmount: string;
};

export type AdminOrderBreakdownAllocationDto = {
  id: string;
  vendorId: string;
  vendorName: string;
  originalVendorId: string;
  assignedVendorId: string;
  allocationStatus: string;
  cancellationReason: string | null;
  reassignmentRequired: boolean;
  fulfillmentStatus: string;
  shippingStatus: string;
  trackingNumber: string | null;
  carrier: string | null;
  trackingUrl: string | null;
  fulfilledAt: string | null;
  shipmentCreatedAt: string | null;
  shipmentUpdatedAt: string | null;
  totalAmount: string;
  lineItems: AdminOrderBreakdownLineItemDto[];
  assignmentHistory: OrderAssignmentHistoryDto[];
  returnRecords: Array<{
    id: string;
    status: string;
    reason: string | null;
    createdAt: string;
    updatedAt: string;
  }>;
  refundRecords: Array<{
    id: string;
    sourceShopifyRefundId: string;
    amount: string;
    status: string;
    createdAt: string;
    updatedAt: string;
  }>;
};

export type AdminOrderBreakdownDto = {
  order: {
    sourceShopifyOrderId: string;
    sourceShopifyOrderNumber: string;
    customerName: string | null;
    customerEmail: string | null;
    totalAmount: string;
    createdAt: string;
    updatedAt: string;
  };
  allocations: AdminOrderBreakdownAllocationDto[];
};
